use_frameworks!

target 'SocialLogins_Example' do
  pod 'SocialLogins', :path => '../'

  target 'SocialLogins_Tests' do
    inherit! :search_paths

    post_install do |installer|
      installer.pods_project.build_configurations.each do |config|
        config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
      end
    end
    
  end
end
